AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation workshop - Linting and testing - VPC and Security Group template (uksb-1q9p31idr)

Parameters:
  MyVpcIpv4Cidr:
    Type: String
    Default: 10.0.0.0/16
    Description: The IPv4 CIDR block you wish to assign to your VPC.

Resources:
  MyVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref 'MyVpcIpv4Cidr'

  MySecurityGroup:
    # This example MySecurityGroup resource contains a circular
    # dependency error: SourceSecurityGroupId references the same
    # MySecurityGroup resource you are describing
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Example Security Group
      SecurityGroupIngress:
        - Description: Example rule to allow tcp/443 traffic from MySecurityGroup
          FromPort: 443
          ToPort: 443
          IpProtocol: tcp
          SourceSecurityGroupId: !Ref 'MySecurityGroup'
      SecurityGroupEgress:
        - Description: Example rule limiting egress traffic to 127.0.0.1/32
          CidrIp: 127.0.0.1/32
          IpProtocol: '-1'
      VpcId: !Ref 'MyVpc'
